### ISSUE TITLE
Not Working properly.

### ISSUE THREAD

**Issue by AlexAnder1946** [naiiveprojects/nv.gd.file_system#8]
when activate the plugin show an error in Output:
  `res://addons/nv.file_system/nv.file_system.gd:72 - Trying to assign value of type 'SplitContainer' to a variable of type 'VSplitContainer'.`

Pressing **Switch  File System Dock** button  
 ```
 scene/main/node.cpp:2777 - Parameter "p_node" is null.
  res://addons/nv.file_system/nv.file_system.gd:109 - Invalid set index 'button_pressed' (on base: 'Nil') with value of type 'bool'.
```

This is what it looks like
![Screenshot from 2023-12-19 00-42-57](https://github.com/naiiveprojects/nv.gd.file_system/assets/87558405/7a9ccd8f-9d23-4ce8-a25f-f6c5e9ada65d)

I am using:
- Godot version: **4.2**
- OS: **Ubuntu**

Thanks for this amazing add-on.

**Comment by illlustr** [comment]
thank you for the report, I think this issue has been fixed in https://github.com/naiiveprojects/nv.gd.file_system/commit/7d5ccb7f067da5f15fe818fd747db7d8945b52b1 , just not updated in assetlib yet, for now you need to manually download this plugin by

```bash
git clone https://github.com/naiiveprojects/nv.gd.file_system/tree/4.x.git
```

or [download this ZIP archive](https://github.com/naiiveprojects/nv.gd.file_system/archive/refs/heads/4.x.zip), let me know if you still have this issue, sorry for inconvenience 😣

**Comment by AlexAnder1946** [comment]
It Works perfectly, thanks 😁
